version: "3.9"

services:
  db:
    image: postgres:14
    volumes:
      - db:/var/lib/postgresql/data
    ports:
      - '5432:5432'
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_DB: bot_db
  bot:
    build: .
    volumes:
      - .:/usr/src/app
    tty: true
    stdin_open: true
    command: ruby main.rb
    depends_on:
      - db
volumes:
  db:

