production:
  bot_name: 'substance_planner_bot'
  api_key: '6750365613:AAG7Ojf9O0xO63zbeZ7OWCc_ODn_2sq84-k'

staging:
  bot_name: 'stage_bot'
  api_key: 'stage_key'

test:
  bot_name: 'test_bot'
  api_key: 'test_key'
