production:
  bot_name: 'substance_planner_bot'
  api_key: '6750365613:AAG7Ojf9O0xO63zbeZ7OWCc_ODn_2sq84-k'

stage:
  bot_name: 'substance_interactions_stage_bot'
  api_key: '7179074746:AAFKvxeMhT7N3GIOTzcVuBd72SQFKjrooJo'

test:
  bot_name: 'test_bot'
  api_key: 'test_key'
