production:
  host: 'db'
  adapter: 'postgresql'
  encoding: utf-8
  database: 'bot_prod'
  password: 'password'
  user: 'postgres'

test:
  host: 'db'
  adapter: 'postgresql'
  encoding: utf-8
  database: 'bot_test'
  password: 'password'
  user: 'postgres'
